server:
  port: 8080
  # Tomcat üretim ortamı ayarları
  tomcat:
    max-threads: 400
    max-connections: 10000
    connection-timeout: 20000
    accept-count: 200
  # Daha agresif kompresyon
  compression:
    min-response-size: 512

# Üretim ortamı yapılandırması
app:
  cors:
    allowed-origins:
      - https://p2p.codeyzer.com
  websocket:
    allowed-origins:
      - https://p2p.codeyzer.com

# Üretim seviyesi loglama
logging:
  level:
    root: INFO
    com.codeyzer.p2p: INFO
    org.springframework.web: WARN 